---
title: Siteleaf Test
timezone: UTC
collections:
  files:
    title: Files
    output: true
  list:
    title: List
    output: true
  people:
    title: People
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
